- name: Template file to td-repo
  template:
    src: ../templates/td.repo.j2
    dest: /etc/yum.repos.d/td.repo
    mode: 644
  vars:
    td_agent_version: "{{ const_td_agent_version }}"
    redhat_version: "{{ ansible_distribution_major_version }}"

- name: Install the package
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
    - libselinux-python

- name: Install td-agent package
  yum:
    name: "td-agent"
    state: present
    enablerepo: treasuredata
  when: not ansible_check_mode
  notify: start td-agent
